# HQ MIR ID Controller API Service Deployment definition
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirid-controller
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: mirid-controller
            deployment: hq
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: mirid-controller
                deployment: hq
        spec:
            containers:
                - name: cloud-hq-ws-mirid-controller
                  image: identifiersorg/cloud-hq-ws-mirid-controller:1.0.0
                  resources:
                      requests:
                          memory: 640Mi
