# HQ deployment Ingress resource for global load balancing
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: hq-deployment
    labels:
        environment: production
        tier: api
        app: hq-deployment
    annotations:
        kubernetes.io/ingress.class: "gce"
        kubernetes.io/ingress.global-static-ip-name: idorg-hq
        ingress.gcp.kubernetes.io/pre-shared-cert: 'cert-iorg-hq-production-web,cert-iorg-hq-production-auth,cert-iorg-hq-production-api-registry,cert-iorg-hq-production-api-mirid'
        kubernetes.io/ingress.allow-http: "false"
spec:
    rules:
    # Registry API rules
    - host: registry.api.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-registry
                  servicePort: 8180
    # MIR ID Controller API Service rules
    - host: mirid.api.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-mirid-controller
                  servicePort: 8181
    # Registry Web Frontend rules
    - host: registry.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-web-hq
                  servicePort: 80
    # Accounts web
    - host: auth.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-keycloak
                  servicePort: 8080
    # Testing endpoint
    - host: test.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-test
                  servicePort: 8080
