# MongoDB HQ Backend definition
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: mongodb
    labels:
        app: mongo
spec:
    ports:
    - port: 27017
      targetPort: 27017
    clusterIP: None
    selector:
        app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongod
spec:
    serviceName: "mongodb"
    replicas: 3
    selector:
        matchLabels:
            app: mongo
    template:
        metadata:
            labels:
                app: mongo
                environment: production
                tier: data-backend
                replicaSet: MainRepSet
        spec:
            containers:
            - name: mongod-container
              image: mongo
              imagePullPolicy: Always
              command:
                  - "mongod"
                  - "--bind_ip"
                  - "0.0.0.0"
                  - "--replSet"
                  - "MainRepSet"
                  - "--auth"
                  - "--clusterAuthMode"
                  - "keyFile"
                  - "--keyFile"
                  - "/etc/secrets_volume/iorg-hq-eu-mongodb.keyfile"
                  - "--setParameter"
                  - "authenticationMechanisms=SCRAM-SHA-1"
              ports:
              - containerPort: 27017
              volumeMounts:
              - name: secrets_volume
                readOnly: true
                mountPath: /etc/secrets_volume
              - name: mongodb-presistent-storage-claim
                mountPath: /data/db
        volumes:
        - name: secrets_volume
            secret:
                secretName: mongodb-auth-bootstrap-data
    VolumeClaimTemplates:
    - metadata:
        name: mongodb-presistent-storage-claim
        annotations:
            volume.beta.kubernetes.io/storage-class: "gce-fast-storage"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
            requests:
                storage: 100Gi
